### ISSUE TITLE
Gender - translate?

### ISSUE THREAD

**Issue by CrazyFreeMan** [Cotonti/lang-ua#9]
https://github.com/Cotonti/lang-ua/blob/master/lang/ua/main.ua.lang.php#L105
Невже українською буде "Пол" а не "Стать" ?

**Comment by Dayver** [comment]
Авжеж ні, просто дуже багато потрібно перкласти і перевірити і тому щоб не мати порожніх значеннь деякі були, в автоматичному режимі, позичені з російського мовного пакету оськільки вона більш близька у розумінні ніж англійскьа (для більшості користувачів).

**Comment by CrazyFreeMan** [comment]
Тоді добре :)
